export type TikTokOrder = {
  'Order ID': string;
  'Order Status': string;
  'Order Substatus': string;
  'Cancelation/Return Type': string;
  'Normal or Pre-order': 'Normal' | 'Pre-order' | string;
  'SKU ID': string;
  'Seller SKU': string;
  'Product Name': string;
  Variation: string;
  Quantity: string;
  'Sku Quantity of return': string;
  'SKU Unit Original Price': string;
  'SKU Subtotal Before Discount': string;
  'SKU Platform Discount': string;
  'SKU Seller Discount': string;
  'SKU Subtotal After Discount': string;
  'Shipping Fee After Discount': string;
  'Original Shipping Fee': string;
  'Shipping Fee Seller Discount': string;
  'Co-Funded Shipping Fee Discount': string;
  'Shipping Fee Platform Discount': string;
  'Payment platform discount': string;
  'Retail Delivery Fee': string;
  Taxes: string;
  'Order Amount': string;
  'Order Refund Amount': string;
  'Created Time': string; // ISO date string
  'Paid Time': string;
  'RTS Time': string;
  'Shipped Time': string;
  'Delivered Time': string;
  'Cancelled Time': string;
  'Cancel By': string;
  'Cancel Reason': string;
  'Fulfillment Type': string;
  'Warehouse Name': string;
  'Tracking ID': string;
  'Delivery Option Type': string;
  'Delivery Option': string;
  'Shipping Provider Name': string;
  'Buyer Message': string;
  'Buyer Username': string;
  Recipient: string;
  'Phone #': string;
  Country: string;
  State: string;
  City: string;
  Zipcode: string;
  'Address Line 1': string;
  'Address Line 2': string;
  'Delivery Instruction': string;
  'Payment Method': string;
  'Weight(kg)': string;
  'Product Category': string;
  'Package ID': string;
  'Seller Note': string;
  'Shipping Information': string;
  'Combined Listing': string;
};
